### ISSUE TITLE
No puedo hacer una peticion, que estoy haciendo mal?

### ISSUE THREAD

**Issue by matiasrosemberg** [Identicum/rest-users-api#2]
![image](https://user-images.githubusercontent.com/14501704/41730360-0876c5f0-7552-11e8-9c4a-119c6ee18480.png)

Me esta tirando este error, que puede estar sucediendo?

Quizás me salte alguna opción que no vi en la reunión del otro día.

**Comment by chupetoide** [comment]
Matías, pasame el mail a Identicum y copialo a Eze.

Saludos
